create table itcharacter
(
    type    smallint
        constraint itcharacter_type_check
            check ((type >= 0) AND (type <= 1)),
    created timestamp(6),
    reward  bigint,
    updated timestamp(6),
    goal    varchar(255),
    id      varchar(255) not null
        primary key,
    name    varchar(255)
);

alter table itcharacter
    owner to postgres;

create table character_notes
(
    it_character_id varchar(255) not null
        constraint fkt822hgnw14mul6wn9asuhaplx
            references itcharacter,
    notes           varchar(255)
);

alter table character_notes
    owner to postgres;

create table itpower
(
    category  smallint
        constraint itpower_category_check
            check ((category >= 0) AND (category <= 3)),
    created   timestamp(6),
    updated   timestamp(6),
    id        varchar(255) not null
        primary key,
    name      varchar(255),
    particles varchar(255)
);

alter table itpower
    owner to postgres;

create table itweapon
(
    type    smallint
        constraint itweapon_type_check
            check ((type >= 0) AND (type <= 12)),
    created timestamp(6),
    power   bigint,
    updated timestamp(6),
    id      varchar(255) not null
        primary key,
    name    varchar(255),
    owner   varchar(255)
);

alter table itweapon
    owner to postgres;

create table power_ideas
(
    ideas       varchar(255),
    it_power_id varchar(255) not null
        constraint fkllcimmpqxhikwq5d5ye1th2t6
            references itpower
);

alter table power_ideas
    owner to postgres;

create table weapon_notes
(
    it_weapon_id varchar(255) not null
        constraint fkb2py6palsbhciul7bua9kvrmy
            references itweapon,
    notes        varchar(255)
);

alter table weapon_notes
    owner to postgres;

create table weapon_titles
(
    it_weapon_id varchar(255) not null
        constraint fka5h5007hfve5dsloy5u6e3wwh
            references itweapon,
    titles       varchar(255)
);

alter table weapon_titles
    owner to postgres;

create table attribute
(
    id    integer generated by default as identity
        primary key,
    value integer,
    items varchar(255),
    name  varchar(255)
);

alter table attribute
    owner to postgres;

create table ituser
(
    created   timestamp(6),
    updated   timestamp(6),
    email     varchar(255),
    id        varchar(255) not null
        primary key,
    last_name varchar(255),
    name      varchar(255),
    password  varchar(255),
    username  varchar(255)
        unique
);

alter table ituser
    owner to postgres;

create table item
(
    is_in_stock boolean      not null,
    created     timestamp(6),
    updated     timestamp(6),
    description varchar(255),
    id          varchar(255) not null
        primary key,
    measurement varchar(255),
    user_id     varchar(255)
        constraint fk3di31qu7fs2ql5l4fwp6rthpd
            references ituser
);

alter table item
    owner to postgres;

create table role
(
    role_name varchar(30)  not null
        unique
        constraint role_role_name_check
            check ((role_name)::text = ANY
                   ((ARRAY ['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])),
    id        varchar(255) not null
        primary key
);

alter table role
    owner to postgres;

create table users_roles
(
    role_id varchar(255) not null
        constraint fkt4v0rrweyk393bdgt107vdx0x
            references role,
    user_id varchar(255) not null
        constraint fkluvr57lisdbxa7kxykag8bws9
            references ituser
);

alter table users_roles
    owner to postgres;