INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo', 3, 'fogo, fogo, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'lava', 3, 'fogo, lama, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo infernal', 3, 'fogo, morte, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo azul', 3, 'fogo, energia, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gua', 3, 'água, água, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'lama', 3, 'água, água, terra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gelo', 3, 'água, energia, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'neve', 3, 'gelo, vento, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'veneno', 3, 'água, água, terra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vapor', 3, 'água, fogo, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sangue', 3, 'água, água, alma', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'nuvem', 3, 'água, vapor, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'água celeste', 3, 'água, vida, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'acido', 3, 'água, veneno, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'tinta', 3, 'água, arco íris, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'oleo', 3, 'água, planta, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vento', 3, 'vento, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'tornado', 3, 'vento, vento, areia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gas', 3, 'vento, veneno, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'estrela', 3, 'gas, luz, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sol', 3, 'estrela, fogo, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'som', 3, 'vento, energia, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'pedra', 3, 'pedra, pedra, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'terra', 3, 'pedra, vento, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'planta', 3, 'terra, água, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'madeira', 3, 'planta, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'papel', 3, 'madeira, água, madeira', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'borracha', 3, 'madeira, corte, madeira', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'areia', 3, 'pedra, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fumaca', 3, 'areia, água, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vidro', 3, 'areia, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'barreira', 3, 'vidro, vidro, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'osso', 3, 'pedra, cristal, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'esqueleto', 3, 'osso, vida, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'metal', 3, 'pedra, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'ouro', 3, 'estrela, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'prata', 3, 'metal, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'mercúrio', 3, 'metal, água, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'cristal', 3, 'metal, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'diamante', 3, 'cristal, calor, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'esmeralda', 3, 'cristal, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'rubi', 3, 'cristal, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'safira', 3, 'cristal, água, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'energia', 3, 'energia, energia, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'escuridão', 3, 'energia, luz, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sombra', 3, 'escuridão, vida, escuridão', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'buraco negro', 3, 'energia, metal, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'absorção', 3, 'buraco negro, escuridão, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'calor', 3, 'energia, fogo, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'frio', 3, 'energia, gelo, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'explosão', 3, 'energia, calor, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'nuclear', 3, 'explosão, vento, explosão', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'eletricidade', 3, 'eletricidade, eletricidade, eletricidade', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'raio', 3, 'eletricidade, nuvem, eletricidade', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'magnetismo', 3, 'eletricidade, metal, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gravidade', 3, 'magnetismo, pedra, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'voo', 3, 'gravidade, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'atração', 3, 'magnetismo, gravidade, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'repulsao', 3, 'magnetismo, vento, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'luz', 3, 'eletricidade, pedra, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'ilusão', 3, 'luz, vida, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'arco íris', 3, 'luz, água, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invisibilidade', 3, 'luz, ilusão, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'teletransporte', 3, 'luz, energia, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vida', 3, 'vida, vida, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'cura', 3, 'vida, energia, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'morte', 3, 'morte, morte, morte', now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'espadas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'escudos', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'borracha', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'corte', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'bloqueio', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'voar', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invisibilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invulnerabilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'intangibilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'asas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sorte', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'clima', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'criação de alvos', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em animais', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas mágicas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas míticas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas divinas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'força', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'velocidade', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'elasticidade', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'regeneração', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'crescimento e diminuição', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'audição', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'visão', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'olfato', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'capacidades físicas aumentadas', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'petrificação', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'telecinese', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'controle mental', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'telepatia', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sonhos', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'aprendizado', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'precognição', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'retrocognição', 0, now(), now());

INSERT INTO itpower_ideas (itpower_id, ideas) VALUES ((SELECT id FROM itpower WHERE name = 'fogo'), 'torre de fogo');
INSERT INTO itpower_ideas (itpower_id, ideas) VALUES ((SELECT id FROM itpower WHERE name = 'fogo'), 'soco de fogo');

INSERT INTO itcharacter (id, name, type, player_name, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character1', 0, 'vini', 'achieve revenge', null, 10000, now(), now());
INSERT INTO itcharacter (id, name, type, player_name, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character2', 0, 'jow', 'gain power', null, 20000, now(), now());
INSERT INTO itcharacter (id, name, type, player_name, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character3', 0, 'luiza', 'make friends', (SELECT id FROM itpower WHERE itpower.name = 'escuridão'), 30000, now(), now());

INSERT INTO itcharacter_notes (itcharacter_id, notes) VALUES ((SELECT id FROM itcharacter WHERE name = 'Character1'), 'Note for Character1'), ((SELECT id FROM itcharacter WHERE name = 'Character1'), 'Another note for Character1');
INSERT INTO itcharacter_notes (itcharacter_id, notes) VALUES ((SELECT id FROM itcharacter WHERE name = 'Character2'), 'Note for Character2');

INSERT INTO itgroup (id, name, description, leader, updated, created) VALUES ('RM_ITGroup_' || gen_random_uuid(), 'Gloriosa', 'Grupo de guerreiros espadachins, adoradores de uma espada antiga conhecida como Gloriosa', '', now(), now());
INSERT INTO itgroup (id, name, description, leader, updated, created) VALUES ('RM_ITGroup_' || gen_random_uuid(), 'Senado', 'Grupo de quatro Senadores escolhidos por cada região do país para governar', '', now(), now());
INSERT INTO itgroup (id, name, description, leader, updated, created) VALUES ('RM_ITGroup_' || gen_random_uuid(), 'Silêncio', 'São caçadores de pessoas com magia, que acreditam que ela deve ser silenciada', '', now(), now());
INSERT INTO itgroup (id, name, description, leader, updated, created) VALUES ('RM_ITGroup_' || gen_random_uuid(), 'Arcanistas', 'São adoradores de pessoas com magia, que acreditam que o futuro é mágico', '', now(), now());

INSERT INTO itgroup_notes (itgroup_id, notes) VALUES ((SELECT id FROM itgroup WHERE name = 'Gloriosa'), 'são adoradores de uma espada antiga que dizem que partiu os céus, separando os países');

INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Ruptura', 0, 10000, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Tormenta', 3, 9999, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Vix', 5, 9998, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Gloriosa', 1, 9997, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Portão', 9, 9996, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Olho do Caçador', 5, 9995, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Lâmina Desafiadora', 2, 9994, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Guardião do Altar', 11, 9993, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Eco das Eras', 10, 9992, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Lâmina do Vento', 1, 9991, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Fio da Noite', 4, 9990, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Profunda', 2, 9899, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Ossada', 8, 9898, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Dente de Umbra', 3, 9897, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Sangue de Caius', 2, 9896, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Luz Sagrada, a Espada Sacrossanta do Arcanjo', 1, 12000, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Barreira, o Escudo Sacrossanto da Proteção Divina', 11, 11000, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Destino, o Arco Sacrossanto da Justiça', 5, 10001, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Triunfo, a Lança Sacrossanta da Santidade', 3, 10500, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Puro, o Cajado Sacrossanto da Pureza Divina', 10, 11500, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Pandora, o Sino Sacrossanto da Esperança', 12, 9500, 'DESCONHECIDO', now(), now());
INSERT INTO itweapon (id, name, type, power, owner, updated, created) VALUES ('RM_ITWeapon_' || gen_random_uuid(), 'Portões, o Martelo Sacrossanto da Ordem', 8, 11001, 'DESCONHECIDO', now(), now());

INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Vix'), 'É uma arma que sobe de nível');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Gloriosa'), 'Diz a lenda que ela foi a responsável por partir os céus durante a separação dos países');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Profunda'), 'Ela possui uma lâmina de cor azul marinho, de rocha oceânica. Diz a lenda que ela é capaz de cortar oceanos. Quanto mais se prolonga o combate, mais poderosa ela fica.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Dente de Umbra'), 'Umbra era um dragão antigo conhecido como O Senhor da Escuridão');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Portão'), 'É uma réplica de uma arma sacrossanta anciã');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Luz Sagrada possui lâmina de aço celeste com alma de arcanjo.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Alto poder destrutivo contra seres das trevas.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Conexão com o portador revela poderes adicionais.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Procura usuários com magia de luz.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Bônus contra trevas, remoção de maldições, bônus de defesa e iluminação.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'Paladinos ganham mais poder ao usá-la.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Barreira, o Escudo Sacrossanto da Proteção Divina'), 'Escudo gerado por Uriel, o Arcanjo dos Portões; Diminui o dano recebido pelo usuário e seus aliados.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Destino, o Arco Sacrossanto da Justiça'), 'Arco gerado por Liriel, a Arcanja da Retidão; Multiplica as flechas, permitindo acertos em área.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Triunfo, a Lança Sacrossanta da Santidade'), 'Lança gerada por Remiel, o Arcanjo da Pureza; Acerto garantido, dano triplicado, sente a pureza no coração dos outros.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Puro, o Cajado Sacrossanto da Pureza Divina'), 'Cajado gerado por Galadriel, o Arcanjo da Cura; Concede imortalidade temporária e grande aumento de poder mágico.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Pandora, o Sino Sacrossanto da Esperança'), 'Sino gerado por Seleniel, a Arcanja das Canções; Concede bônus em CA, TAC0, vida, dano, cura, resistência e magias para o portador e seus aliados.');
INSERT INTO itweapon_notes (itweapon_id, notes) VALUES ((SELECT id FROM itweapon WHERE name = 'Portões, o Martelo Sacrossanto da Ordem'), 'Martelo gerado por Rafiel, o Arcanjo Juíz; Causa um dano estrondoso.');

INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Vix'), 'Arco da Ascenção');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Vix'), 'Arco do Infinito');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Portão'), 'O Martelo da Ordem');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Profunda'), 'A Lâmina das Profundezas');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Luz Sagrada, a Espada Sacrossanta do Arcanjo'), 'A Espada da Luz');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Barreira, o Escudo Sacrossanto da Proteção Divina'), 'O Escudo da Proteção');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Destino, o Arco Sacrossanto da Justiça'), 'O Arco da Justiça');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Triunfo, a Lança Sacrossanta da Santidade'), 'A Lança da Santidade');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Pandora, o Sino Sacrossanto da Esperança'), 'O Sino da Esperança');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Puro, o Cajado Sacrossanto da Pureza Divina'), 'O Cajado da Pureza');
INSERT INTO itweapon_titles (itweapon_id, titles) VALUES ((SELECT id FROM itweapon WHERE name = 'Portões, o Martelo Sacrossanto da Ordem'), 'O Martelo da Ordem');

INSERT INTO itcity (id, name, title, leader, size, updated, created) VALUES ('RM_ITCity_' || gen_random_uuid(), 'Fortana', 'A Capital do Turismo', 'Merongatar', 3, now(), now());
INSERT INTO itcity (id, name, title, leader, size, updated, created) VALUES ('RM_ITCity_' || gen_random_uuid(), 'Elbana', 'A Capital Mágica', 'Alto Benito', 5, now(), now());
INSERT INTO itcity (id, name, title, leader, size, updated, created) VALUES ('RM_ITCity_' || gen_random_uuid(), 'Dantana', 'A Capital do Combate', 'Ramirez', 6, now(), now());

INSERT INTO itcity_curiosities (itcity_id, curiosities) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Querem ser a Capital Mágica de Solana');

INSERT INTO itcity_groups (itcity_id, groups) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Seguidores de Tiamat');
INSERT INTO itcity_groups (itcity_id, groups) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Alcatéia');

INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Fortana'), 'é a maior e mais importante cidade de Solana, sendo considerada a grande capital');
INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Fortana'), 'é o centro intelectual de Solana, onde estão os maiores estudiosos de todas as áreas');
INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Fortana'), 'é o maior centro comercial do Reino');
INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Elbana'), 'possui as melhores criaturas mágicas de Solana');
INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Elbana'), 'só pode ser acessada por montarias aladas');
INSERT INTO itcity_notes (itcity_id, notes) VALUES ((SELECT id from itcity where name = 'Elbana'), 'é o maior fornecedor de minérios mágicos do país');

INSERT INTO itcity_people (itcity_id, people) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Merongatar');
INSERT INTO itcity_people (itcity_id, people) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Morgana');
INSERT INTO itcity_people (itcity_id, people) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Lirin');
INSERT INTO itcity_people (itcity_id, people) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Celma');

INSERT INTO itcity_places (itcity_id, places) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Taberna Alces Saltitantes');
INSERT INTO itcity_places (itcity_id, places) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Taberna Falcões Silvestres');
INSERT INTO itcity_places (itcity_id, places) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Taberna Taça Dourada');
INSERT INTO itcity_places (itcity_id, places) VALUES ((SELECT id from itcity where name = 'Fortana'), 'Boticário');