INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo', 3, 'fogo, fogo, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'lava', 3, 'fogo, lama, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo infernal', 3, 'fogo, morte, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fogo azul', 3, 'fogo, energia, fogo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gua', 3, 'água, água, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'lama', 3, 'água, água, terra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gelo', 3, 'água, energia, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'neve', 3, 'gelo, vento, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'veneno', 3, 'água, água, terra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vapor', 3, 'água, fogo, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sangue', 3, 'água, água, alma', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'nuvem', 3, 'água, vapor, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'água celeste', 3, 'água, vida, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'acido', 3, 'água, veneno, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'tinta', 3, 'água, arco íris, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'oleo', 3, 'água, planta, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vento', 3, 'vento, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'tornado', 3, 'vento, vento, areia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gas', 3, 'vento, veneno, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'estrela', 3, 'gas, luz, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sol', 3, 'estrela, fogo, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'som', 3, 'vento, energia, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'corte', 3, 'vento, energia, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'pedra', 3, 'pedra, pedra, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'terra', 3, 'pedra, vento, água', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'planta', 3, 'terra, água, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'madeira', 3, 'planta, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'papel', 3, 'madeira, água, madeira', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'borracha', 3, 'madeira, corte, madeira', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'areia', 3, 'pedra, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'fumaca', 3, 'areia, água, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vidro', 3, 'areia, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'barreira', 3, 'vidro, vidro, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'osso', 3, 'pedra, cristal, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'esqueleto', 3, 'osso, vida, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'metal', 3, 'pedra, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'ouro', 3, 'estrela, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'prata', 3, 'metal, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'mercúrio', 3, 'metal, água, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'cristal', 3, 'metal, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'diamante', 3, 'cristal, calor, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'esmeralda', 3, 'cristal, vento, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'rubi', 3, 'cristal, fogo, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'safira', 3, 'cristal, água, pedra', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'energia', 3, 'energia, energia, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'escuridão', 3, 'energia, luz, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sombra', 3, 'escuridão, vida, escuridão', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'buraco negro', 3, 'energia, metal, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'absorção', 3, 'buraco negro, escuridão, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'calor', 3, 'energia, fogo, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'frio', 3, 'energia, gelo, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'explosão', 3, 'energia, calor, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'nuclear', 3, 'explosão, vento, explosão', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'eletricidade', 3, 'eletricidade, eletricidade, eletricidade', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'raio', 3, 'eletricidade, nuvem, eletricidade', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'magnetismo', 3, 'eletricidade, metal, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'gravidade', 3, 'magnetismo, pedra, magnetismo', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'voo', 3, 'gravidade, vento, vento', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'atração', 3, 'magnetismo, gravidade, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'repulsao', 3, 'magnetismo, vento, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'luz', 3, 'eletricidade, pedra, energia', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'ilusão', 3, 'luz, vida, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'arco íris', 3, 'luz, água, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invisibilidade', 3, 'luz, ilusão, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'teletransporte', 3, 'luz, energia, luz', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'vida', 3, 'vida, vida, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'cura', 3, 'vida, energia, vida', now(), now());
INSERT INTO itpower (id, name, category, particles, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'morte', 3, 'morte, morte, morte', now(), now());

INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'espadas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'escudos', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'borracha', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'corte', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'bloqueio', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'voar', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invisibilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'invulnerabilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'intangibilidade', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'asas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sorte', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'clima', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'criação de alvos', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em animais', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas mágicas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas míticas', 2, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'transformação em criaturas divinas', 2, now(), now());

INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'força', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'velocidade', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'elasticidade', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'regeneração', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'crescimento e diminuição', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'audição', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'visão', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'olfato', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'capacidades físicas aumentadas', 1, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'petrificação', 1, now(), now());

INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'telecinese', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'controle mental', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'telepatia', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'sonhos', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'aprendizado', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'precognição', 0, now(), now());
INSERT INTO itpower (id, name, category, updated, created) VALUES ('RM_ITPower_' || gen_random_uuid(), 'retrocognição', 0, now(), now());

INSERT INTO itpower_ideas (itpower_id, ideas) VALUES ((SELECT id FROM itpower WHERE name = 'fogo'), 'torre de fogo');
INSERT INTO itpower_ideas (itpower_id, ideas) VALUES ((SELECT id FROM itpower WHERE name = 'fogo'), 'soco de fogo');

INSERT INTO itcharacter (id, name, type, player, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character1', 0, 'vini', 'achieve revenge', null, 10000, now(), now());
INSERT INTO itcharacter (id, name, type, player, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character2', 0, 'jow', 'gain power', null, 20000, now(), now());
INSERT INTO itcharacter (id, name, type, player, goal, itpower_id, reward, updated, created) VALUES ('RM_ITCharacter_' || gen_random_uuid(), 'Character3', 0, 'luiza', 'make friends', (SELECT id FROM itpower WHERE itpower.name = 'escuridão'), 30000, now(), now());

INSERT INTO itcharacter_notes (itcharacter_id, notes) VALUES ((SELECT id FROM itcharacter WHERE name = 'Character1'), 'Note for Character1'), ((SELECT id FROM itcharacter WHERE name = 'Character1'), 'Another note for Character1'), ((SELECT id FROM itcharacter WHERE name = 'Character2'), 'Note for Character2');

