server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: rpgmaker-back
          uri: lb://RPGMAKER-BACK
          predicates:
            - Path=/rpgmaker-back/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedHeaders: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              maxAge: 30
        - id: content-back
          uri: lb://CONTENT-BACK
          predicates:
            - Path=/content-back/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedHeaders: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              maxAge: 30

rm:
  serviceRegistry:
    username: serviceregistry
    password: vento123

eureka:
  client:
    service-url:
      defaultZone: 'http://${rm.serviceRegistry.username}:${rm.serviceRegistry.password}@localhost:8761/eureka'
    enabled: true
  instance:
    hostname: localhost