import type { Metadata } from "next";
import localFont from "next/font/local";
import { CharacterProvider } from "./context/CharacterContext";
import { CityProvider } from "./context/CityContext";
import { UtilsProvider } from "./context/UtilsContext";
import "./ui/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CharacterProvider>
          <CityProvider>
            <UtilsProvider>
              {children}
            </UtilsProvider>
          </CityProvider>
        </CharacterProvider>
      </body>
    </html>
  );
}
