server:
  port: 8082
  servlet:
    context-path: '/content-back/'

spring:
  profiles:
    active: dev
  application:
    name: content-back
  data:
    web:
      pageable:
        page-parameter: 0
        default-page-size: 50
  datasource:
    url: jdbc:postgresql://localhost:5432/rpgmakerdb
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_content_schema_history
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      jdbc:
        lob.non-contextual-creation: true
    properties:
      originPrefix: RM
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    br.isertech.com.content-back: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    web: DEBUG

rpg-maker:
  serviceRegistry:
    username: serviceregistry
    password: vento123
  auth:
    jwtSecret: test
    jwtExpirationMs: 14400000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: 'http://${rpg-maker.serviceRegistry.username}:${rpg-maker.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 100
        waitDurationInOpenState: 60s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        max-attempts: 3
        waitDuration: 5s

clients:
  auth-client:
    name: 'ituser-client'
    url: 'localhost:8080/rpgmaker-back'